name: PushImages
on:
  push:
    branches:
      - 'main'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set the value
        id: step_one
        run: |
          echo "image=vorkurk/nginx-spa:$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ env.image }}
